Manhattan\Bundle\ContentBundle\Entity\Document:
    type:  entity
    table: content_document
    repositoryClass: Manhattan\Bundle\ContentBundle\Entity\Repository\DocumentRepository

    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true

    manyToOne:
        content:
            targetEntity: Manhattan\Bundle\ContentBundle\Entity\Content
            inversedBy: documents
            joinColumn:
                name: content_id
                referencedColumnName: id
                onDelete: SET NULL
