Manhattan\Bundle\ContentBundle\Entity\Document:
    type:  entity
    table: content_document
    repositoryClass: Manhattan\Bundle\ContentBundle\Entity\Repository\DocumentRepository

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mime_type:
            type: string
            length: 255
        filename:
            type: string
            length: 255
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
        content:
            targetEntity: Manhattan\Bundle\ContentBundle\Entity\Content
            inversedBy: documents
            joinColumn:
                name: content_id
                referencedColumnName: id
                onDelete: SET NULL

    lifecycleCallbacks:
        prePersist:
            - preUpload
            - prePersist
        preUpdate:
            - preUpdateAsset
            - preUpdate
        postPersist:
            - upload
        postUpdate:
            - replace
        preRemove:
            - storeFilenameForRemove
        postRemove:
            - removeUpload
