Manhattan\Bundle\ContentBundle\Entity\Image:
    type:  entity
    table: content_image

    manyToOne:
        content:
            targetEntity: Manhattan\Bundle\ContentBundle\Entity\Content
            inversedBy: images
            joinColumn:
                name: content_id
                referencedColumnName: id
                onDelete: SET NULL
