AGBContent:
    resource: "@AGBContentBundle/Controller/ContentController.php"
    type:     annotation

AGBContentDocuments:
    resource: "@AGBContentBundle/Controller/DocumentController.php"
    type:     annotation
