<?php

namespace Manhattan\Bundle\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    /**
     * Returns Document with joined Content
     *
     * @param  int      $id
     * @return Document
     */
    public function findOneByIdJoinContent($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT document, content FROM ManhattanContentBundle:Document document
                LEFT JOIN document.content content
                WHERE document.id = :id'
            )->setParameters(array(
                'id' => $id
        ));

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
